const GetHelp = [
  { headline: "Canadian Crisis Centers", overview: "Numbers for Support" },
  { headline: "United States Crisis Centers", overview: "Numbers for Support" },
  { headline: "International Crisis Centers", overview: "Numbers for Support" },
  {
    headline: "Coping with Suicidal Thoughts",
    overview: "Find ways to cope with sadness.",
  },
  {
    headline: "How can I help someone",
    overview: "Find ways to cope with sadness.",
  },
  { headline: "myths & facts", overview: "Numbers for Support" },
  { headline: "E-Counselling", overview: "Numbers for Support" },
  { headline: "Self Management", overview: "Numbers for Support" },
  { headline: "Warning Signs", overview: "Numbers for Support" },
  { headline: "Search for a Professional", overview: "Numbers for Support" },
];
const resources = [
  {
    headline: "Coping With Suicidal Thoughts",
    overview: "Find ways to cope with sadness",
  },
  { headline: "Search For A Professional", overview: "Numbers for Support" },
  { headline: "Online Counselling", overview: "Numbers for Support" },
  { headline: "Self Management", overview: "Numbers for Support" },
  { headline: "How Can I Help Someone?", overview: "Numbers for Support" },
  { headline: "Warning Signs", overview: "Numbers for Support" },
  { headline: "Depression", overview: "Numbers for Support" },
  { headline: "Myths & Facts", overview: "Numbers for Support" },
  { headline: "Addiction", overview: "Numbers for Support" },
  { headline: "Anxiety", overview: "Numbers for Support" },
  {
    headline: "Post Traumatic Stress Disorder",
    overview: "Numbers for Support",
  },
  { headline: "Grief", overview: "Numbers for Support" },
  { headline: "Teens & Youth", overview: "Numbers for Support" },
  { headline: "Resources For Parents", overview: "Numbers for Support" },
  { headline: "College Students", overview: "Numbers for Support" },
  { headline: "LGBTQ2+", overview: "Numbers for Support" },
  { headline: "Indigenous Issues", overview: "Numbers for Support" },
  { headline: "Seniors", overview: "Numbers for Support" },
  { headline: "Men", overview: "Numbers for Support" },
  { headline: "Veterans & Military", overview: "Numbers for Support" },
  { headline: "Refugees", overview: "Numbers for Support" },
  { headline: "Attempt Survivors", overview: "Numbers for Support" },
  { headline: "Survivors of Suicide Loss", overview: "Numbers for Support" },
  { headline: "Bereaved Support", overview: "Numbers for Support" },
  { headline: "After Suicide Loss", overview: "Numbers for Support" },
  { headline: "Educators", overview: "Numbers for Support" },
  { headline: "Health Professionals", overview: "Numbers for Support" },
  { headline: "First Responders", overview: "Numbers for Support" },
  { headline: "Care Givers", overview: "Numbers for Support" },
  { headline: "Media Professionals", overview: "Numbers for Support" },
  { headline: "Workplace Employers", overview: "Numbers for Support" },
  { headline: "Resource Organizations", overview: "Number for Support" },
];

// Export the resources array
export { resources, GetHelp };
